# simplified haskell-ci Travis setup
# see also https://github.com/haskell-CI/haskell-ci

language: haskell
sudo: enabled

cache:
  directories:
   - $HOME/.cabal/store

matrix:
  include:
    - ghc: "8.6.5"
      cabal: 2.4
    - ghc: "8.4.4"
      cabal: 2.4
    - ghc: "8.2.2"
      cabal: 2.4
    - ghc: "8.0.2"
      cabal: 2.4

install:
 - cabal --version
 - ghc --version

script:
 - cabal v2-update
 - cabal v2-build
